# Generated by Django 3.2.13 on 2022-07-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('verify_email', models.EmailField(max_length=254)),
                ('text', models.TextField()),
            ],
        ),
    ]
