# Generated by Django 3.2.13 on 2022-07-21 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_remove_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
