# Generated by Django 3.2.13 on 2022-07-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
