# Generated by Django 3.2.13 on 2022-07-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0003_auto_20220714_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=256),
        ),
    ]
