# Generated by Django 3.2.13 on 2022-07-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0006_auto_20220721_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='task',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
