# Generated by Django 3.2.13 on 2022-07-22 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0007_user_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='task',
            new_name='login_times',
        ),
    ]
