# Generated by Django 3.2.13 on 2022-07-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0008_rename_task_user_login_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_times',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=10),
        ),
    ]
